---
- hosts: 127.0.0.1
  connection: local

- name: Install Docker, Docker-Compose, etc
  import_playbook: install-docker.yml

- name: Generate certificates for Fleet
  import_playbook: generate-certs.yml
  
- name: Pull images referenced in docker-compose.yml
  import_playbook: pull-fleet-images.yml

- name: Update Fleet configs and build/restart containers
  import_playbook: update-fleet-containers.yml

- name: Add a desktop shortcut for Fleet
  import_playbook: add-fleet-shortcut.yml  