---
- name: Update Kolide Fleet Containers
  hosts: 127.0.0.1
  connection: local
  gather_facts: no
  become: yes
  become_method: sudo

  tasks:

- import_playbook: update-local-checkout.yml
- import_playbook: sync-files.yml

  - name: docker-compose up
    docker_compose:
      project_src: /opt/kolide
      recreate: always
      state: present
